name: Tests
on:
  push:
    branches:
      # Match SemVer major release branches, e.g. "2.x" or ".x"
      - '[0-9]+.x'
      - 'main'
      - 'next'
      - 'alpha'
      - 'beta'
      - 'renovate/**'
      - '!all-contributors/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

  eslint:
    name: ESLint
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Lint
        run: yarn lint:eslint

  typescript:
    name: TypeScript
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Lint
        run: tsc -v && yarn lint:typescript

  test:
    name: Test
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: yarn test:ci

  build:
    name: Build
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: yarn build
